### ISSUE TITLE
Update node-lambda NPM package to local path use

### ISSUE THREAD

**Issue by rhernand3z** [NYPL/refile-request-service#1]
Currently the requirement is for `node-lambda` to use the global install. That creates problems when other services are using other versions of `node-lambda`. The de facto standard should be to install a new instance of `node-lambda` for every new project that specifies the version in package.json. When running deploy commands, they should target the `/node_modules/.bin/node-lambda` cli commands.

CC: @gkallenberg

**Comment by nodanaonlyzuul** [comment]
Heyo. I know @rhernand3z self-assigned this but in case anyone takes it on and needs an example...[pcdm-store-updater's package.json](https://github.com/NYPL-discovery/pcdm-store-updater/blob/master/package.json) has node-lambda in its `devDependencies` and uses `./node_modules/.bin/node-lambda` in its deploy commands.
